/*
 * New World Trade Skill Tracker
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Gathering struct {
	Logging    int32 `json:"logging,omitempty" bson:"smelting,omitempty"`
	Mining     int32 `json:"mining,omitempty" bson:"mining,omitempty"`
	Fishing    int32 `json:"fishing,omitempty" bson:"fishing,omitempty"`
	Harvesting int32 `json:"harvesting,omitempty" bson:"harvesting,omitempty"`
	Skinning   int32 `json:"skinning,omitempty" bson:"skinning,omitempty"`
}
