/*
 * New World Trade Skill Tracker
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Crafting struct {
	Weaponsmithing int32 `json:"weaponsmithing,omitempty" bson:"weaponsmithing,omitempty"`
	Armoring       int32 `json:"armoring,omitempty" bson:"armoring,omitempty"`
	Engineering    int32 `json:"engineering,omitempty" bson:"engineering,omitempty"`
	Jewelcrafting  int32 `json:"jewelcrafting,omitempty" bson:"jewelcrafting,omitempty"`
	Arcana         int32 `json:"arcana,omitempty" bson:"arcana,omitempty"`
	Cooking        int32 `json:"cooking,omitempty" bson:"cooking,omitempty"`
	Furnishing     int32 `json:"furnishing,omitempty" bson:"furnishing,omitempty"`
}
