/*
 * New World Trade Skill Tracker
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Refining struct {
	Smelting       int32 `json:"smelting,omitempty" bson:"smelting,omitempty"`
	Woodworking    int32 `json:"woodworking,omitempty" bson:"woodworking,omitempty"`
	Leatherworking int32 `json:"leatherworking,omitempty" bson:"leatherworking,omitempty"`
	Weaving        int32 `json:"weaving,omitempty" bson:"weaving,omitempty"`
	Stonecutting   int32 `json:"stonecutting,omitempty" bson:"stonecutting,omitempty"`
}
